Repository hong-yura/WorkForUs-Project, pull requests merged in 2022-11, with the labels that each got.

#179 Feature/admin/hyr
  workforus/src/main/java/site/workforus/forus/admin/controller/AdminFileUploadController.java
  workforus/src/main/java/site/workforus/forus/admin/controller/DeptController.java
  workforus/src/main/java/site/workforus/forus/admin/model/AdminFileUploadDTO.java
  workforus/src/main/java/site/workforus/forus/admin/model/DeptDTO.java
  workforus/src/main/java/site/workforus/forus/admin/service/AdminFileUploadService.java
  workforus/src/main/java/site/workforus/forus/admin/service/DeptService.java
  workforus/src/main/java/site/workforus/forus/mapper/AdminFileUploadMapper.java
  workforus/src/main/java/site/workforus/forus/mapper/DeptMapper.java
  workforus/src/main/resources/mybatis/mapper/adminFileUploadMapper.xml
  workforus/src/main/resources/mybatis/mapper/deptMapper.xml
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  workforus/src/main/webapp/WEB-INF/views/admin/dept-add.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept-manage.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept-modify.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/thema.jsp
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
  workforus/src/main/webapp/resources/images/logo/default.png
  workforus/src/main/webapp/resources/js/pages/admin/department/department-add.js
  workforus/src/main/webapp/resources/js/pages/admin/department/department-delete.js
  workforus/src/main/webapp/resources/js/pages/admin/department/department-modify.js
  workforus/src/main/webapp/resources/js/pages/admin/department/departments-list.js
  workforus/src/main/webapp/resources/js/pages/admin/department/index.js
  workforus/src/main/webapp/resources/js/pages/admin/department/result-modal.js
  workforus/src/main/webapp/resources/js/pages/admin/thema/logo-upload.js
  workforus/src/main/webapp/resources/js/pages/admin/thema/select-logo.js
Labels: ✨FEATURE

#181 Setting : .gitignore 수정
  .gitignore
Labels: ⚙SETTING

#182 Feature/board like/lbs
  workforus/src/main/java/site/workforus/forus/board/controller/BoardController.java
  workforus/src/main/java/site/workforus/forus/board/controller/PostLikeController.java
  workforus/src/main/java/site/workforus/forus/board/model/PostLikeDTO.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardPostService.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardPostMapper.java
  workforus/src/main/resources/mybatis/mapper/boardPostMapper.xml
  workforus/src/main/webapp/WEB-INF/views/board/post-add.jsp
  workforus/src/main/webapp/WEB-INF/views/board/post-detail.jsp
  workforus/src/main/webapp/WEB-INF/views/board/post-modify.jsp
  workforus/src/main/webapp/resources/js/pages/board/board-like.js
  workforus/src/main/webapp/resources/js/pages/board/index.js
Labels: ✨FEATURE, Status: Complete

#185 Fix/commute/kje
  workforus/src/main/java/site/workforus/forus/commute/controller/CommuteController.java
  workforus/src/main/java/site/workforus/forus/commute/service/CommuteService.java
  workforus/src/main/java/site/workforus/forus/mapper/CommuteMapper.java
  workforus/src/main/resources/mybatis/mapper/commuteMapper.xml
  workforus/src/main/webapp/WEB-INF/views/commute/commute.jsp
  workforus/src/main/webapp/WEB-INF/views/commute/commuteList.jsp
  workforus/src/main/webapp/resources/js/pages/commute/commute.js
Labels: 🐛BUG

#186 Update README
  README.md
Labels: 📝DOCS

#190 Delete forus.iml
  workforus/forus.iml
Labels: 🔥DEL

#188 Update .gitignore
  .gitignore
Labels: ⚙SETTING

#192 Fix : url 수정
  workforus/pom.xml
  workforus/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
  workforus/src/main/webapp/resources/js/pages/calendar/App.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddCalendarFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddScheduleFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddShareCalendarFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/CalendarInfoFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/ScheduleInfoFrame.js
Labels: 🐛BUG, ➕ADD

#195 Delete forus.iml
  workforus/forus.iml
Labels: 🔥DEL
