Repository hong-yura/WorkForUs-Project, pull requests merged in 2022-09, with the labels that each got.

#13 docs : 화면창을 줄여도 navigation이 고정되도록 수정
  workforus/src/main/webapp/resources/css/app.css
Labels: ➕ADD

#15 feature : header 추가 및 수정
  workforus/src/main/webapp/WEB-INF/views/home.jsp
  workforus/src/main/webapp/WEB-INF/views/module/header.jsp
  workforus/src/main/webapp/resources/css/app.css
  workforus/src/main/webapp/resources/css/bootstrap.css
Labels: 🎨DESIGN

#21 feature : 게시판DTO 추가
  workforus/src/main/java/site/workforus/forus/board/model/BoardCategoryDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardParticipDTO.java
Labels: ✨FEATURE

#24 feature : 캘린더 페이지 추가
  workforus/src/main/java/site/workforus/forus/calendar/controller/CalendarController.java
  workforus/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
  workforus/src/main/webapp/resources/css/pages/calendar.css
  workforus/src/main/webapp/resources/js/pages/calendar/App.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarHeader.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarMain.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarMenu.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarSubMenu.js
  workforus/src/main/webapp/resources/js/pages/calendar/index.js
  workforus/src/main/webapp/resources/js/pages/calendar/utils/formatYearMonth.js
Labels: ✨FEATURE, 🎨DESIGN, ➕ADD

#27 Feature : dept 기능을 위한 패키지 추가 및 mapping
  workforus/pom.xml
  workforus/src/main/java/site/workforus/forus/dept/controller/DeptController.java
  workforus/src/main/java/site/workforus/forus/dept/model/DeptDTO.java
  workforus/src/main/java/site/workforus/forus/dept/service/DeptService.java
  workforus/src/main/java/site/workforus/forus/mapper/deptMapper.java
  workforus/src/main/resources/mybatis/mapper/deptMapper.xml
  workforus/src/main/resources/mybatis/mapper/employee.xml
  workforus/src/main/resources/mybatis/mybatis-config.xml
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  workforus/src/main/webapp/WEB-INF/spring/root-context.xml
Labels: ✨FEATURE, ♻REFACTOR, ⚙SETTING, 💻In Progress

#28 Feature : 근태관리용 object 생성
  workforus/src/main/java/site/workforus/forus/commute/controller/CommuteController.java
  workforus/src/main/java/site/workforus/forus/commute/model/CommuteDTO.java
  workforus/src/main/java/site/workforus/forus/commute/service/CommuteService.java
  workforus/src/main/java/site/workforus/forus/mapper/commuteMapper.java
  workforus/src/main/resources/mybatis/mapper/commuteMapper.xml
Labels: ✨FEATURE

#33 Chore : 의존성 추가
  workforus/pom.xml
Labels: ➕ADD

#34 Add : typeAlias 추가
  workforus/src/main/resources/mybatis/mybatis-config.xml
Labels: ➕ADD

#37 Feature : 주소록 object 생성
  workforus/src/main/java/site/workforus/forus/address/controller/AddressController.java
  workforus/src/main/java/site/workforus/forus/address/model/AddressDTO.java
  workforus/src/main/java/site/workforus/forus/address/service/AddressService.java
  workforus/src/main/java/site/workforus/forus/mapper/AddressMapper.java
  workforus/src/main/resources/mybatis/mapper/addressMapper.xml
Labels: ✨FEATURE, Status: In Progress

#38 Feature : job object 생성
  workforus/src/main/java/site/workforus/forus/job/controller/JobController.java
  workforus/src/main/java/site/workforus/forus/job/model/JobDTO.java
  workforus/src/main/java/site/workforus/forus/job/service/JobService.java
  workforus/src/main/java/site/workforus/forus/mapper/JobMapper.java
  workforus/src/main/resources/mybatis/mapper/jobMapper.xml
Labels: ✨FEATURE, Status: In Progress

#42 Refactor : lombok Annotation 적용 and 파일명 수정
  workforus/src/main/java/site/workforus/forus/dept/model/DeptDTO.java
  workforus/src/main/java/site/workforus/forus/dept/service/DeptService.java
  workforus/src/main/java/site/workforus/forus/mapper/DeptMapper.java
  workforus/src/main/resources/mybatis/mapper/deptMapper.xml
Labels: ♻REFACTOR

#44 Refactor : mybatis typealias 방식 수정
  workforus/src/main/java/site/workforus/forus/address/model/AddressDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardCategoryDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardParticipDTO.java
  workforus/src/main/java/site/workforus/forus/calendar/model/CalendarDTO.java
  workforus/src/main/java/site/workforus/forus/commute/model/CommuteDTO.java
  workforus/src/main/java/site/workforus/forus/dept/model/DeptDTO.java
  workforus/src/main/java/site/workforus/forus/employee/model/EmpDTO.java
  workforus/src/main/java/site/workforus/forus/global/dto/ResponseDTO.java
  workforus/src/main/java/site/workforus/forus/job/model/JobDTO.java
  workforus/src/main/resources/mybatis/mybatis-config.xml
Labels: ♻REFACTOR

#46 Add/header&nav/hyr
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
  workforus/src/main/webapp/resources/css/app.css
Labels: ➕ADD

#52 Chore : mockito 의존성 추가
  workforus/pom.xml
  workforus/src/main/java/site/workforus/forus/admin/controller/AdminController.java
  workforus/src/main/webapp/WEB-INF/views/admin/logo.jsp
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
Labels: ➕ADD, 🧪TEST

#48 feature : empMapper 추가 (#47)
  workforus/src/main/java/site/workforus/forus/mapper/EmpMapper.java
  workforus/src/main/resources/mybatis/mapper/empMapper.xml
  workforus/src/main/resources/mybatis/mybatis-config.xml
Labels: ✨FEATURE

#54 feature : 게시판 object 추가
  workforus/src/main/java/site/workforus/forus/board/controller/BoardController.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardCategoryDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardParticipDTO.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardService.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardMapper.java
  workforus/src/main/resources/mybatis/mapper/boardMapper.xml
  workforus/src/main/webapp/WEB-INF/views/board/list.jsp
  workforus/src/main/webapp/resources/css/pages/board.css
Labels: ✨FEATURE, 🎨DESIGN

#50 feature : calendar object 추가 (#49)
  workforus/src/main/java/site/workforus/forus/calendar/controller/CalendarController.java
  workforus/src/main/java/site/workforus/forus/calendar/controller/ScheduleController.java
  workforus/src/main/java/site/workforus/forus/calendar/model/CalendarDTO.java
  workforus/src/main/java/site/workforus/forus/calendar/model/CalendarShareDTO.java
  workforus/src/main/java/site/workforus/forus/calendar/model/ScheduleDTO.java
  workforus/src/main/java/site/workforus/forus/calendar/service/CalendarService.java
  workforus/src/main/java/site/workforus/forus/calendar/service/CalendarShareService.java
  workforus/src/main/java/site/workforus/forus/calendar/service/ScheduleService.java
  workforus/src/main/java/site/workforus/forus/mapper/CalendarMapper.java
  workforus/src/main/java/site/workforus/forus/mapper/CalendarShareMapper.java
  workforus/src/main/java/site/workforus/forus/mapper/ScheduleMapper.java
  workforus/src/main/resources/mybatis/mapper/calendarMapper.xml
  workforus/src/main/resources/mybatis/mapper/calendarShareMapper.xml
  workforus/src/main/resources/mybatis/mapper/scheduleMapper.xml
Labels: ✨FEATURE

#58 feature : EmpDTO 수정 (#57)
  workforus/src/main/java/site/workforus/forus/employee/model/EmpDTO.java
Labels: ✨FEATURE

#63 Chore : mybatis-config and dependency 추가
  workforus/pom.xml
  workforus/src/main/resources/mybatis/mybatis-config.xml
Labels: ➕ADD

#65 feature : 게시판DTO 수정
  workforus/src/main/java/site/workforus/forus/board/model/BoardCategoryDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardParticipDTO.java
Labels: ✨FEATURE

#71 fix : xml 수정
  workforus/src/main/java/site/workforus/forus/FooBar.java
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  workforus/src/main/webapp/WEB-INF/spring/root-context.xml
  workforus/src/main/webapp/WEB-INF/web.xml
Labels: 🐛BUG

#70 Feature: 근태기록
  workforus/src/main/java/site/workforus/forus/commute/controller/CommuteController.java
  workforus/src/main/java/site/workforus/forus/commute/model/CommuteDTO.java
  workforus/src/main/java/site/workforus/forus/commute/service/CommuteService.java
  workforus/src/main/java/site/workforus/forus/mapper/commuteMapper.java
  workforus/src/main/resources/mybatis/mapper/commuteMapper.xml
Labels: ✨FEATURE, ➕ADD

#72 Bug Fix : 페이지 화면이 안 뜨는 에러 픽스
  workforus/src/main/java/site/workforus/forus/FooBar.java
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  workforus/src/main/webapp/WEB-INF/spring/root-context.xml
  workforus/src/main/webapp/WEB-INF/web.xml
Labels: 🐛BUG

#73 fix : 돌아가자 bug fix
  workforus/src/main/java/site/workforus/forus/FooBar.java
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  workforus/src/main/webapp/WEB-INF/spring/root-context.xml
  workforus/src/main/webapp/WEB-INF/web.xml
Labels: 🐛BUG

#76 fix : seucurity 관련 문제 해결
  workforus/src/main/java/site/workforus/forus/FooBar.java
  workforus/src/main/webapp/WEB-INF/spring/appServlet/security-context.xml
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  workforus/src/main/webapp/WEB-INF/web.xml
Labels: 🐛BUG

#79 fix : static 적용 실패 이슈 해결
  workforus/src/main/java/site/workforus/forus/board/model/BoardDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardParticipDTO.java
  workforus/src/main/webapp/WEB-INF/views/module/header.jsp
Labels: 🐛BUG

#80 Feature/salary object/kje
  workforus/src/main/java/site/workforus/forus/commute/controller/SalaryController.java
  workforus/src/main/java/site/workforus/forus/commute/model/SalaryDTO.java
  workforus/src/main/java/site/workforus/forus/commute/service/CommuteService.java
  workforus/src/main/java/site/workforus/forus/commute/service/SalaryService.java
  workforus/src/main/java/site/workforus/forus/mapper/CommuteMapper.java
  workforus/src/main/java/site/workforus/forus/mapper/SalaryMapper.java
  workforus/src/main/resources/mybatis/mapper/commuteMapper.xml
  workforus/src/main/resources/mybatis/mapper/salaryMapper.xml
Labels: ✨FEATURE, Status: Complete

#82 feature: 채팅 화면 구현 (#81)
  workforus/src/main/java/site/workforus/forus/chat/controller/ChatController.java
  workforus/src/main/webapp/WEB-INF/views/chat/chat.jsp
  workforus/src/main/webapp/resources/css/chat.css
  workforus/src/main/webapp/resources/css/style.css
  workforus/src/main/webapp/resources/js/chat.js
Labels: ✨FEATURE

#83 Feature: 조직도(부서 및 부서 상세) 조회
  workforus/src/main/java/site/workforus/forus/admin/controller/DeptController.java
  workforus/src/main/java/site/workforus/forus/admin/controller/JobController.java
  workforus/src/main/java/site/workforus/forus/admin/controller/LogoController.java
  workforus/src/main/java/site/workforus/forus/admin/controller/MembersMandgeController.java
  workforus/src/main/java/site/workforus/forus/admin/service/DeptService.java
  workforus/src/main/java/site/workforus/forus/mapper/DeptMapper.java
  workforus/src/main/resources/mybatis/mapper/deptMapper.xml
  workforus/src/main/webapp/WEB-INF/views/admin/dept_add.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept_manage.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept_modify.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/members.jsp
  workforus/src/main/webapp/resources/css/pages/admin.css
  workforus/src/main/webapp/resources/css/pages/jui-ui.min.classic.css
  workforus/src/main/webapp/resources/js/pages/admin/jui-core.min.js
  workforus/src/main/webapp/resources/js/pages/admin/jui-ui.min.js
Labels: ✨FEATURE, Status: Complete

#84 Feature: address 수정중
  workforus/src/main/java/site/workforus/forus/address/controller/AddressController.java
  workforus/src/main/java/site/workforus/forus/address/service/AddressService.java
  workforus/src/main/java/site/workforus/forus/mapper/AddressMapper.java
  workforus/src/main/resources/mybatis/mapper/addressMapper.xml
  workforus/src/main/webapp/WEB-INF/views/address/address.jsp
  workforus/src/main/webapp/WEB-INF/views/address/indvAddress.jsp
  workforus/src/main/webapp/resources/css/pages/address.css
Labels: ✨FEATURE, 🎨DESIGN, Status: In Progress

#86 Refactor: head and navigation Update
  workforus/src/main/webapp/WEB-INF/spring/appServlet/security-context.xml
  workforus/src/main/webapp/WEB-INF/views/home.jsp
  workforus/src/main/webapp/WEB-INF/views/module/head.jsp
  workforus/src/main/webapp/WEB-INF/views/module/header.jsp
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
Labels: 🎨DESIGN, ➕ADD, ♻REFACTOR

#89 Refactor : admin and address page URL Update
  workforus/src/main/java/site/workforus/forus/address/controller/AddressController.java
  workforus/src/main/java/site/workforus/forus/admin/controller/DeptController.java
  workforus/src/main/java/site/workforus/forus/admin/controller/LogoController.java
  workforus/src/main/webapp/WEB-INF/views/address/address.jsp
  workforus/src/main/webapp/WEB-INF/views/address/personal_address.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept_manage.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/logo.jsp
Labels: 🎨DESIGN, ♻REFACTOR

#91 Feature : 월급 기능 구현
  workforus/pom.xml
  workforus/src/main/java/site/workforus/forus/commute/controller/SalaryController.java
  workforus/src/main/java/site/workforus/forus/commute/model/SalaryDTO.java
  workforus/src/main/java/site/workforus/forus/commute/service/SalaryService.java
  workforus/src/main/java/site/workforus/forus/mapper/SalaryMapper.java
  workforus/src/main/resources/mybatis/mapper/salaryMapper.xml
Labels: ✨FEATURE, ➕ADD, Status: In Progress

#92 style : 근태관리 및 월급 조회 화면 구현
  workforus/src/main/webapp/WEB-INF/views/commute/commute.jsp
  workforus/src/main/webapp/WEB-INF/views/commute/salary.jsp
Labels: 🎨DESIGN, Status: In Progress

#94 Feature : 캘린더 추가 및 조회, 일정 생성 기능 추가
  workforus/src/main/java/site/workforus/forus/calendar/controller/CalendarController.java
  workforus/src/main/java/site/workforus/forus/calendar/model/ScheduleDTO.java
  workforus/src/main/java/site/workforus/forus/calendar/service/CalendarShareService.java
  workforus/src/main/java/site/workforus/forus/mapper/CalendarShareMapper.java
  workforus/src/main/resources/mybatis/mapper/calendarMapper.xml
  workforus/src/main/resources/mybatis/mapper/calendarShareMapper.xml
  workforus/src/main/resources/mybatis/mapper/scheduleMapper.xml
  workforus/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
  workforus/src/main/webapp/resources/js/pages/calendar/App.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarMain.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarMenu.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarSubMenu.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarSubShareMenu.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddCalendarFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddCalendarModal.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddScheduleFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddScheduleModal.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/ModalPortal.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/ScheduleInfo.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/ScheduleInfoModal.js
  workforus/src/main/webapp/resources/js/pages/calendar/utils/eventConverter.js
  workforus/src/main/webapp/resources/js/pages/calendar/utils/eventReverter.js
  workforus/src/main/webapp/resources/js/pages/calendar/utils/setEndDate.js
  workforus/src/main/webapp/resources/js/pages/calendar/utils/setTime.js
  workforus/src/test/java/site/workforus/forus/calendar/service/CalendarControllerTest.java
Labels: ✨FEATURE, ➕ADD

#96 Chore : pom.xml에 webjars 추가
  workforus/pom.xml
  workforus/src/main/webapp/WEB-INF/views/module/head.jsp
Labels: ➕ADD

#99 Refactor : calendar.jsp 및 js 수정
  workforus/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarSubMenu.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarSubShareMenu.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddCalendarFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddScheduleFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/ScheduleInfo.js
Labels: ♻REFACTOR

#103 fix : pom, servlet 추가
  workforus/pom.xml
  workforus/src/main/java/site/workforus/forus/socket/Chatting.java
  workforus/src/main/java/site/workforus/forus/socket/WebSocketConfig.java
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: ➕ADD

#104 feature : 게시글 작성, 게시글 댓글
  workforus/pom.xml
  workforus/src/main/java/site/workforus/forus/board/controller/BoardController.java
  workforus/src/main/java/site/workforus/forus/board/controller/SummernoteUploadImageController.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardPostDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/PostCommentDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/PostUploadFileDTO.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardPostService.java
  workforus/src/main/java/site/workforus/forus/board/service/PostCommentService.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardPostMapper.java
  workforus/src/main/resources/mybatis/mapper/boardPostMapper.xml
  workforus/src/main/webapp/WEB-INF/views/board/add.jsp
  workforus/src/main/webapp/WEB-INF/views/board/detail.jsp
  workforus/src/main/webapp/WEB-INF/views/board/list.jsp
  workforus/src/main/webapp/WEB-INF/views/board/modify.jsp
  workforus/src/main/webapp/resources/css/pages/board.css
  workforus/src/main/webapp/resources/js/pages/board/index.js
Labels: ✨FEATURE

#105 fix : servlet-context 추가
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: 🐛BUG

#107 feature : 개인페이지 모달 구현 (#106)
  workforus/src/main/java/site/workforus/forus/employee/model/LoginVO.java
  workforus/src/main/webapp/WEB-INF/views/home.jsp
  workforus/src/main/webapp/resources/css/pages/info.css
  workforus/src/main/webapp/resources/js/pages/chat/chat.js
  workforus/src/main/webapp/resources/js/pages/info/info.js
  workforus/src/main/webapp/resources/js/pages/login/login.js
  workforus/src/main/webapp/resources/js/pages/login/signup.js
Labels: ✨FEATURE

#108 feature : 근태관리 이번달기록 불러오기
  workforus/src/main/java/site/workforus/forus/commute/controller/CommuteController.java
  workforus/src/main/java/site/workforus/forus/commute/service/CommuteService.java
  workforus/src/main/java/site/workforus/forus/mapper/CommuteMapper.java
  workforus/src/main/resources/mybatis/mapper/commuteMapper.xml
  workforus/src/main/webapp/WEB-INF/views/commute/commute.jsp
  workforus/src/main/webapp/WEB-INF/views/commute/salary.jsp
  workforus/src/main/webapp/resources/css/pages/tooltip.css
Labels: ✨FEATURE, Status: Complete

#109 Feature/admin/hyr
  workforus/src/main/java/site/workforus/forus/admin/controller/DeptController.java
  workforus/src/main/java/site/workforus/forus/admin/service/DeptService.java
  workforus/src/main/java/site/workforus/forus/mapper/DeptMapper.java
  workforus/src/main/webapp/WEB-INF/views/admin/dept_add.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept_manage.jsp
Labels: ✨FEATURE, 🎨DESIGN, Status: In Progress

#110 Docs : calendar 관련 Sql 쿼리문 추가
  workforus/sql/calednar/CALENDARS.sql
  workforus/sql/calednar/CALENDAR_SHARES.sql
  workforus/sql/calednar/SCHEDULES.sql
Labels: 📝DOCS, Status: Complete

#116 Feature : 조직도(부서) 수정 기능 수정중
  workforus/src/main/java/site/workforus/forus/admin/controller/DeptController.java
  workforus/src/main/resources/mybatis/mapper/deptMapper.xml
  workforus/src/main/webapp/WEB-INF/views/admin/dept_manage.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept_modify.jsp
Labels: ✨FEATURE, Status: In Progress

#119 Feature : 부서 추가 기능 수정중
  workforus/src/main/java/site/workforus/forus/admin/controller/DeptController.java
  workforus/src/main/webapp/WEB-INF/views/admin/dept_add.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept_manage.jsp
Labels: ✨FEATURE, Status: In Progress

#117 Docs : 근태관리용 SQL문 추가
  workforus/sql/commute/COMMUTE.sql
  workforus/sql/commute/SALARY.sql
Labels: 📝DOCS, Status: Complete

#124 feature : 댓글 작성, 게시글 삭제 기능 구현
  workforus/src/main/java/site/workforus/forus/board/controller/BoardController.java
  workforus/src/main/java/site/workforus/forus/board/controller/SummernoteUploadImageController.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardPostService.java
  workforus/src/main/java/site/workforus/forus/board/service/PostCommentService.java
  workforus/src/main/java/site/workforus/forus/board/service/UploadFileService.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardPostMapper.java
  workforus/src/main/resources/mybatis/mapper/boardPostMapper.xml
  workforus/src/main/webapp/WEB-INF/views/board/add.jsp
  workforus/src/main/webapp/WEB-INF/views/board/detail.jsp
  workforus/src/main/webapp/WEB-INF/views/board/list.jsp
  workforus/src/main/webapp/WEB-INF/views/board/modify.jsp
  workforus/src/main/webapp/WEB-INF/views/board_md/comment_module.jsp
  workforus/src/main/webapp/WEB-INF/views/board_md/delete_modal.jsp
  workforus/src/main/webapp/resources/css/pages/board.css
  workforus/src/main/webapp/resources/images/board/고심.jpg
  workforus/src/main/webapp/resources/js/pages/board/index.js
Labels: ✨FEATURE

#125 feature : 채팅 구현 (송수신만 구현) (#122)
  workforus/src/main/java/site/workforus/forus/socket/Chatting.java
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  workforus/src/main/webapp/WEB-INF/views/chat/chat.jsp
  workforus/src/main/webapp/resources/css/pages/chat.css
Labels: ✨FEATURE

#129 Feature : 메일 송수신 및 화면구현
  workforus/src/main/java/site/workforus/forus/mail/controller/MailController.java
  workforus/src/main/java/site/workforus/forus/mail/model/SendMailDTO.java
  workforus/src/main/java/site/workforus/forus/mail/service/MailService.java
  workforus/src/main/java/site/workforus/forus/mapper/SendMailMapper.java
  workforus/src/main/resources/mybatis/mapper/sendMailMapper.xml
  workforus/src/main/resources/mybatis/mybatis-config.xml
  workforus/src/main/webapp/WEB-INF/views/mail/mailDetail.jsp
  workforus/src/main/webapp/WEB-INF/views/mail/mailHome.jsp
  workforus/src/main/webapp/WEB-INF/views/mail/mailSend.jsp
  workforus/src/main/webapp/WEB-INF/views/mail/mailWrite.jsp
Labels: ✨FEATURE, 🎨DESIGN, Status: In Progress

#132 feature : SockJS, Stomp 기본설정 (#131)
  workforus/pom.xml
  workforus/src/main/java/site/workforus/forus/chat/controller/ChatRoomController.java
  workforus/src/main/java/site/workforus/forus/chat/controller/StompChatController.java
  workforus/src/main/java/site/workforus/forus/chat/model/ChatMessageDTO.java
  workforus/src/main/java/site/workforus/forus/chat/model/ChatRoomDTO.java
  workforus/src/main/java/site/workforus/forus/chat/service/ChatService.java
  workforus/src/main/java/site/workforus/forus/socket/Chatting.java
  workforus/src/main/java/site/workforus/forus/socket/WebSocketConfig.java
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  workforus/src/main/webapp/WEB-INF/views/chat/chat.jsp
Labels: ✨FEATURE

#133 Refactor : navigation Update
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
Labels: ♻REFACTOR, Status: Complete

#134 Feature: 부서 추가, 수정 기능 수정중
  workforus/src/main/java/site/workforus/forus/admin/controller/DeptController.java
  workforus/src/main/java/site/workforus/forus/admin/service/DeptService.java
  workforus/src/main/java/site/workforus/forus/mapper/DeptMapper.java
  workforus/src/main/resources/mybatis/mapper/deptMapper.xml
  workforus/src/main/webapp/WEB-INF/views/admin/dept_add.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept_manage.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept_modify.jsp
  workforus/src/main/webapp/resources/css/pages/admin.css
Labels: ✨FEATURE, Status: In Progress

#135 Feature : 메일 DTO추가 및 시큐리티연결
  workforus/src/main/java/site/workforus/forus/commute/controller/CommuteController.java
  workforus/src/main/java/site/workforus/forus/commute/controller/SalaryController.java
  workforus/src/main/java/site/workforus/forus/mail/controller/MailController.java
  workforus/src/main/java/site/workforus/forus/mail/model/ReceiveMailDTO.java
  workforus/src/main/java/site/workforus/forus/mail/service/MailService.java
  workforus/src/main/java/site/workforus/forus/mapper/SendMailMapper.java
  workforus/src/main/resources/mybatis/mapper/sendMailMapper.xml
  workforus/src/main/webapp/WEB-INF/views/mail/mailDetail.jsp
  workforus/src/main/webapp/WEB-INF/views/mail/mailHome.jsp
Labels: 🐛BUG, ✨FEATURE

#139 [BE] : 게시글 수정 기능 및 댓글 토글 기능 추가
  workforus/src/main/java/site/workforus/forus/board/controller/BoardController.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardPostDTO.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardPostService.java
  workforus/src/main/java/site/workforus/forus/board/service/PostCommentService.java
  workforus/src/main/java/site/workforus/forus/board/service/UploadFileService.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardPostMapper.java
  workforus/src/main/resources/mybatis/mapper/boardPostMapper.xml
  workforus/src/main/webapp/WEB-INF/views/board/add.jsp
  workforus/src/main/webapp/WEB-INF/views/board/detail.jsp
  workforus/src/main/webapp/WEB-INF/views/board/list.jsp
  workforus/src/main/webapp/WEB-INF/views/board/modify.jsp
  workforus/src/main/webapp/WEB-INF/views/board_md/comment_module.jsp
  workforus/src/main/webapp/resources/css/pages/board.css
  workforus/src/main/webapp/resources/js/pages/board/index.js
Labels: ✨FEATURE

#140 Design : 로고 설정 page
  workforus/src/main/webapp/WEB-INF/views/admin/logo.jsp
  workforus/src/main/webapp/resources/css/pages/admin.css
Labels: 🎨DESIGN

#143 feature : 게시판 로그인 객체 연결 및 navbar 적용
  workforus/src/main/java/site/workforus/forus/board/controller/BoardController.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardDTO.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardPostService.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardService.java
  workforus/src/main/java/site/workforus/forus/board/service/PostCommentService.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardMapper.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardPostMapper.java
  workforus/src/main/resources/mybatis/mapper/boardMapper.xml
  workforus/src/main/resources/mybatis/mapper/boardPostMapper.xml
  workforus/src/main/webapp/WEB-INF/views/board/detail.jsp
  workforus/src/main/webapp/WEB-INF/views/board/list.jsp
  workforus/src/main/webapp/WEB-INF/views/board/modify.jsp
  workforus/src/main/webapp/WEB-INF/views/board_md/comment_module.jsp
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
  workforus/src/main/webapp/resources/js/pages/board/index.js
Labels: ✨FEATURE

#145 feature : 설문 메인 페이지 구현 및 설문조사 url 연동
  workforus/src/main/java/site/workforus/forus/mapper/SurveyMapper.java
  workforus/src/main/java/site/workforus/forus/survey/controller/SurveyController.java
  workforus/src/main/java/site/workforus/forus/survey/model/Paging.java
  workforus/src/main/java/site/workforus/forus/survey/model/SurveyDTO.java
  workforus/src/main/java/site/workforus/forus/survey/model/SurveyQuestionDTO.java
  workforus/src/main/java/site/workforus/forus/survey/service/SurveyService.java
  workforus/src/main/resources/mybatis/mapper/surveyMapper.xml
  workforus/src/main/resources/mybatis/mybatis-config.xml
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
  workforus/src/main/webapp/WEB-INF/views/survey/survey_detail.jsp
  workforus/src/main/webapp/WEB-INF/views/survey/survey_list.jsp
  workforus/src/main/webapp/resources/css/pages/survey.css
  workforus/src/main/webapp/resources/js/pages/survey/index.js
Labels: ✨FEATURE, 🎨DESIGN

#148 feature: Stomp를 이용한 채팅 구현 (#147)
  workforus/src/main/java/site/workforus/forus/chat/controller/ChatRoomController.java
  workforus/src/main/java/site/workforus/forus/chat/controller/StompChatController.java
  workforus/src/main/java/site/workforus/forus/chat/model/ChatRoomDTO.java
  workforus/src/main/java/site/workforus/forus/chat/service/ChatService.java
  workforus/src/main/java/site/workforus/forus/mapper/ChatMapper.java
  workforus/src/main/resources/mybatis/mapper/chatMapper.xml
  workforus/src/main/webapp/WEB-INF/views/chat/chat.jsp
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
Labels: ✨FEATURE

#149 Fix : 근태관리 및 월급조회 이슈 수정
  workforus/src/main/java/site/workforus/forus/commute/controller/CommuteController.java
  workforus/src/main/java/site/workforus/forus/commute/model/SalaryDTO.java
  workforus/src/main/java/site/workforus/forus/commute/service/CommuteService.java
  workforus/src/main/java/site/workforus/forus/commute/service/SalaryService.java
  workforus/src/main/java/site/workforus/forus/mapper/SalaryMapper.java
  workforus/src/main/resources/mybatis/mapper/salaryMapper.xml
  workforus/src/main/webapp/WEB-INF/views/commute/commute.jsp
  workforus/src/main/webapp/WEB-INF/views/commute/commuteList.jsp
Labels: 🐛BUG, Status: In Progress

#150 fix : 게시판 네비게이션에 session 객체 불러오기
  workforus/src/main/java/site/workforus/forus/HomeController.java
  workforus/src/main/java/site/workforus/forus/board/controller/BoardController.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardPostService.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardMapper.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardPostMapper.java
  workforus/src/main/resources/mybatis/mapper/boardMapper.xml
  workforus/src/main/resources/mybatis/mapper/boardPostMapper.xml
  workforus/src/main/webapp/WEB-INF/views/board/add.jsp
  workforus/src/main/webapp/WEB-INF/views/board/detail.jsp
  workforus/src/main/webapp/WEB-INF/views/board/list.jsp
  workforus/src/main/webapp/WEB-INF/views/board/modify.jsp
  workforus/src/main/webapp/WEB-INF/views/board_md/comment_module.jsp
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
  workforus/src/main/webapp/resources/css/pages/board.css
Labels: 🐛BUG, ✨FEATURE

#151 Fix : 근태관리 네비 수정
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
Labels: 🐛BUG

#153 feature : 캘린더 페이지에 로그인된 유저 정보 적용 및 캘린더, 일정 공유 (#152)
  workforus/src/main/java/site/workforus/forus/calendar/controller/CalendarController.java
  workforus/src/main/java/site/workforus/forus/calendar/service/CalendarService.java
  workforus/src/main/java/site/workforus/forus/calendar/service/CalendarShareService.java
  workforus/src/main/java/site/workforus/forus/mapper/CalendarMapper.java
  workforus/src/main/resources/mybatis/mapper/calendarMapper.xml
  workforus/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
  workforus/src/main/webapp/resources/css/pages/calendar.css
  workforus/src/main/webapp/resources/js/pages/calendar/App.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarMenu.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarSubMenu.js
  workforus/src/main/webapp/resources/js/pages/calendar/components/CalendarSubShareMenu.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddCalendarFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddCalendarModal.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddScheduleFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddShareCalendarFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddShareCalendarModal.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/CalendarInfoFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/ScheduleInfoFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/utils/eventReverter.js
Labels: ✨FEATURE, 🎨DESIGN, Status: In Progress

#154 Feature : 관리자 파일 업로드를 위한 객체 생성
  workforus/src/main/java/site/workforus/forus/admin/controller/AdminFileUploadController.java
  workforus/src/main/java/site/workforus/forus/admin/model/AdminFileUploadDTO.java
  workforus/src/main/java/site/workforus/forus/admin/service/AdminFileUploadService.java
  workforus/src/main/java/site/workforus/forus/mapper/AdminFileUploadMapper.java
  workforus/src/main/resources/mybatis/mapper/adminFileUploadMapper.xml
  workforus/src/main/webapp/WEB-INF/views/admin/logo.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/thema.jsp
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
Labels: Status: In Progress

#155 Feature: 부서 추가, 수정 기능 구현
  workforus/src/main/java/site/workforus/forus/admin/controller/DeptController.java
  workforus/src/main/java/site/workforus/forus/admin/model/DeptVO.java
  workforus/src/main/java/site/workforus/forus/admin/service/DeptService.java
  workforus/src/main/java/site/workforus/forus/mapper/DeptMapper.java
  workforus/src/main/resources/mybatis/mapper/deptMapper.xml
  workforus/src/main/webapp/WEB-INF/views/admin/dept_add.jsp
  workforus/src/main/webapp/WEB-INF/views/admin/dept_modify.jsp
  workforus/src/main/webapp/resources/js/pages/admin/department/department-add.js
  workforus/src/main/webapp/resources/js/pages/admin/department/department-delete.js
  workforus/src/main/webapp/resources/js/pages/admin/department/department-modify.js
  workforus/src/main/webapp/resources/js/pages/admin/department/departments-list.js
  workforus/src/main/webapp/resources/js/pages/admin/department/jui-core.min.js
  workforus/src/main/webapp/resources/js/pages/admin/department/jui-ui.min.js
Labels: ✨FEATURE, Status: Complete

#156 Fix : 오류 수정
  workforus/src/main/java/site/workforus/forus/admin/controller/DeptController.java
  workforus/src/main/webapp/WEB-INF/views/admin/dept_manage.jsp
Labels: 🐛BUG, Status: Complete

#157 Feature : 게시글 좋아요 구현
  workforus/sql/board/tb_board_categorys.sql
  workforus/sql/board/tb_board_posts.sql
  workforus/sql/board/tb_boards.sql
  workforus/sql/board/tb_post_comments.sql
  workforus/sql/board/tb_post_files.sql
  workforus/sql/board/tb_post_participation_list.sql
  workforus/src/main/java/site/workforus/forus/board/controller/PostLikeController.java
  workforus/src/main/java/site/workforus/forus/board/model/PagingDTO.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardPostService.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardPostMapper.java
  workforus/src/main/resources/mybatis/mapper/boardMapper.xml
  workforus/src/main/resources/mybatis/mapper/boardPostMapper.xml
  workforus/src/main/webapp/WEB-INF/views/board/board_add.jsp
  workforus/src/main/webapp/WEB-INF/views/board/detail.jsp
  workforus/src/main/webapp/WEB-INF/views/board/list.jsp
  workforus/src/main/webapp/resources/js/pages/board/index.js
Labels: 🐛BUG, ✨FEATURE

#158 Refacotr : 헤더 수정
  workforus/src/main/java/site/workforus/forus/HomeController.java
  workforus/src/main/java/site/workforus/forus/mail/controller/MailController.java
  workforus/src/main/java/site/workforus/forus/mail/service/MailService.java
  workforus/src/main/java/site/workforus/forus/mapper/SendMailMapper.java
  workforus/src/main/resources/mybatis/mapper/sendMailMapper.xml
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
Labels: ♻REFACTOR

#159 Feature : 메일 휴지통 및 답장 기능 추가
  workforus/src/main/java/site/workforus/forus/mail/controller/MailController.java
  workforus/src/main/java/site/workforus/forus/mail/service/MailService.java
  workforus/src/main/java/site/workforus/forus/mapper/SendMailMapper.java
  workforus/src/main/resources/mybatis/mapper/sendMailMapper.xml
  workforus/src/main/webapp/WEB-INF/views/mail/mailDetail.jsp
  workforus/src/main/webapp/WEB-INF/views/mail/mailHome.jsp
  workforus/src/main/webapp/WEB-INF/views/mail/mailOutSend.jsp
  workforus/src/main/webapp/WEB-INF/views/mail/mailSend.jsp
  workforus/src/main/webapp/WEB-INF/views/mail/mailSendDetail.jsp
  workforus/src/main/webapp/WEB-INF/views/mail/mailTemp.jsp
  workforus/src/main/webapp/WEB-INF/views/mail/mailWrite.jsp
Labels: ✨FEATURE

#161 feature : info 조회, 수정 (#160)
  workforus/src/main/java/site/workforus/forus/employee/controller/EmpController.java
  workforus/src/main/java/site/workforus/forus/employee/model/EmpDTO.java
  workforus/src/main/java/site/workforus/forus/employee/service/EmpService.java
  workforus/src/main/java/site/workforus/forus/mapper/EmpMapper.java
  workforus/src/main/resources/mybatis/mapper/empMapper.xml
  workforus/src/main/webapp/WEB-INF/views/chat/chat.jsp
  workforus/src/main/webapp/WEB-INF/views/login/info.jsp
  workforus/src/main/webapp/resources/css/pages/info.css
  workforus/src/main/webapp/resources/js/pages/info/info.js
Labels: ✨FEATURE

#164 공용 주소록 조회 수정중
  workforus/sql/address/ADDRESS.sql
  workforus/src/main/java/site/workforus/forus/address/controller/AddressController.java
  workforus/src/main/java/site/workforus/forus/address/model/AddressDTO.java
  workforus/src/main/java/site/workforus/forus/address/service/AddressService.java
  workforus/src/main/java/site/workforus/forus/employee/model/LoginVO.java
  workforus/src/main/java/site/workforus/forus/mapper/AddressMapper.java
  workforus/src/main/resources/mybatis/mapper/addressMapper.xml
  workforus/src/main/webapp/WEB-INF/views/address/address.jsp
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
Labels: 🐛BUG, 📝DOCS, ✨FEATURE, Status: In Progress

#167 Feature : 게시판 생성 기능
  workforus/src/main/java/site/workforus/forus/board/controller/BoardController.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardDTO.java
  workforus/src/main/java/site/workforus/forus/board/model/BoardParticipDTO.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardService.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardMapper.java
  workforus/src/main/resources/mybatis/mapper/boardMapper.xml
  workforus/src/main/resources/mybatis/mapper/boardPostMapper.xml
  workforus/src/main/webapp/WEB-INF/views/board/add.jsp
  workforus/src/main/webapp/WEB-INF/views/board/board_add.jsp
  workforus/src/main/webapp/WEB-INF/views/board/detail.jsp
  workforus/src/main/webapp/WEB-INF/views/board/list.jsp
  workforus/src/main/webapp/WEB-INF/views/board/modify.jsp
  workforus/src/main/webapp/WEB-INF/views/board_md/delete_modal.jsp
  workforus/src/main/webapp/resources/js/pages/board/index.js
Labels: ✨FEATURE

#169 feature : 회원가입 시 이메일 인증 구현 (#168)
  workforus/pom.xml
  workforus/src/main/java/site/workforus/forus/employee/controller/EmpController.java
  workforus/src/main/java/site/workforus/forus/employee/service/MailSendService.java
  workforus/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  workforus/src/main/webapp/WEB-INF/views/login/signup.jsp
  workforus/src/main/webapp/resources/js/pages/login/signup.js
Labels: ✨FEATURE, 🎨DESIGN

#170 Docs : 메일 관련 sql문 추가
  workforus/sql/mail/RECEIVE_MAIL.sql
  workforus/sql/mail/SEND_MAIL.sql
  workforus/sql/mail/TEMP_MAILBOX.sql
Labels: 📝DOCS, Status: Complete

#171 Fix : commute에서 발생한 이슈 해결
  workforus/src/main/java/site/workforus/forus/commute/service/SalaryService.java
  workforus/src/main/webapp/WEB-INF/views/commute/commute.jsp
Labels: 🐛BUG, Status: Complete

#172 Fix : 출퇴근 기록 안되는 이슈 해결
  workforus/src/main/webapp/WEB-INF/views/commute/commute.jsp
  workforus/src/main/webapp/WEB-INF/views/commute/commuteCalendar.jsp
  workforus/src/main/webapp/resources/js/pages/commute/commute.js
Labels: 🐛BUG

#173 Feature : 설문조사 질문 가져오기
  workforus/src/main/java/site/workforus/forus/board/controller/BoardController.java
  workforus/src/main/java/site/workforus/forus/board/service/BoardService.java
  workforus/src/main/java/site/workforus/forus/mapper/BoardMapper.java
  workforus/src/main/java/site/workforus/forus/mapper/SurveyMapper.java
  workforus/src/main/java/site/workforus/forus/survey/controller/SurveyController.java
  workforus/src/main/java/site/workforus/forus/survey/model/ObjectiveDistractorDTO.java
  workforus/src/main/java/site/workforus/forus/survey/model/SurveyQuestionDTO.java
  workforus/src/main/java/site/workforus/forus/survey/service/SurveyService.java
  workforus/src/main/resources/mybatis/mapper/surveyMapper.xml
  workforus/src/main/webapp/WEB-INF/views/survey/survey_add.jsp
  workforus/src/main/webapp/WEB-INF/views/survey/survey_detail.jsp
  workforus/src/main/webapp/WEB-INF/views/survey/survey_list.jsp
  workforus/src/main/webapp/WEB-INF/views/survey/survey_question.jsp
  workforus/src/main/webapp/resources/css/pages/survey.css
Labels: ✨FEATURE

#175 feature : 채팅 및 프로필 사진 수정 (#174)
  workforus/src/main/java/site/workforus/forus/chat/controller/StompChatController.java
  workforus/src/main/java/site/workforus/forus/employee/controller/EmpController.java
  workforus/src/main/java/site/workforus/forus/employee/service/EmpService.java
  workforus/src/main/java/site/workforus/forus/mapper/EmpMapper.java
  workforus/src/main/java/site/workforus/forus/socket/Chatting.java
  workforus/src/main/java/site/workforus/forus/socket/WebSocketConfig.java
  workforus/src/main/resources/mybatis/mapper/empMapper.xml
  workforus/src/main/webapp/WEB-INF/views/chat/chat.jsp
  workforus/src/main/webapp/WEB-INF/views/login/info.jsp
  workforus/src/main/webapp/resources/css/pages/info.css
  workforus/src/main/webapp/resources/images/faces/static.png
  workforus/src/main/webapp/resources/images/login/background.jpg
  workforus/src/main/webapp/resources/images/login/background2.jpg
  workforus/src/main/webapp/resources/images/login/background3.jpg
Labels: 🐛BUG, ✨FEATURE

#177 feature : 메인화면 추가, 캘린더 url 배포된 url로 수정
  workforus/src/main/java/site/workforus/forus/HomeController.java
  workforus/src/main/webapp/WEB-INF/views/home.jsp
  workforus/src/main/webapp/resources/images/samples/best_emp.png
  workforus/src/main/webapp/resources/images/samples/byebye.png
  workforus/src/main/webapp/resources/js/pages/calendar/App.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddCalendarFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddScheduleFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/AddShareCalendarFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/CalendarInfoFrame.js
  workforus/src/main/webapp/resources/js/pages/calendar/modal/ScheduleInfoFrame.js
  workforus/src/test/java/site/workforus/forus/calendar/service/CalendarControllerTest.java
Labels: 🎨DESIGN, ➕ADD, ♻REFACTOR
