Repository hong-yura/WorkForUs-Project, pull requests merged in 2023-01, with the labels that each got.

#204 Feature : 사원별 직급 조회
  workforus/src/main/java/site/workforus/forus/admin/controller/JobController.java
  workforus/src/main/java/site/workforus/forus/admin/model/JobDTO.java
  workforus/src/main/java/site/workforus/forus/admin/service/JobService.java
  workforus/src/main/java/site/workforus/forus/mapper/JobMapper.java
  workforus/src/main/resources/mybatis/mapper/jobMapper.xml
  workforus/src/main/webapp/WEB-INF/views/module/navigation.jsp
  workforus/src/main/webapp/resources/js/pages/admin/job/jobs-list.js
Labels: ✨FEATURE

#202 Feature : 시큐리티 권한 기능 수정중
  workforus/src/main/java/site/workforus/forus/employee/model/AuthDTO.java
  workforus/src/main/java/site/workforus/forus/employee/model/EmpDTO.java
  workforus/src/main/java/site/workforus/forus/employee/service/EmpService.java
  workforus/src/main/java/site/workforus/forus/mapper/EmpMapper.java
  workforus/src/main/resources/mybatis/mapper/empMapper.xml
  workforus/src/main/webapp/WEB-INF/spring/appServlet/security-context.xml
Labels: Status: In Progress

#208 Refactor : 주소록 조회 시 부서명 표시와 추가 버튼 모달 수정
  workforus/src/main/webapp/WEB-INF/views/address/address.jsp
  workforus/src/main/webapp/WEB-INF/views/address/department.jsp
  workforus/src/main/webapp/WEB-INF/views/address/personal.jsp
  workforus/src/main/webapp/resources/js/pages/address/common.js
  workforus/src/main/webapp/resources/js/pages/address/department.js
Labels: ♻REFACTOR

#210 fix : ChatMessageDTO 추가 (#209)
  workforus/src/main/java/site/workforus/forus/chat/model/ChatMessageDTO.java
Labels: 🐛BUG

#212 feature : setAllowedOrigins 추가 (#211)
  workforus/src/main/java/site/workforus/forus/chat/config/StompWebSocketConfig.java
Labels: ➕ADD

#214 Fix : meta추가
  workforus/src/main/webapp/WEB-INF/views/chat/chat.jsp
Labels: ➕ADD

#213 fix : 수정
  workforus/src/main/webapp/WEB-INF/views/chat/chat.jsp
Labels: 🐛BUG
